server:
  port: 8088

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/dasboot
    username: sa
    password:
    driver-class-name: org.h2.Driver
    max-active: 10
    max-idle: 8
    max-wait: 10000
    min-evictable-idle-time-millis: 1000
    min-idle: 8
    time-between-eviction-runs-millis: 1
  jpa:
    hibernate:
      ddl-auto: none
      show_sql: true

flyway:
  baseline-on-migrate: true


datasource:
  flyway:
    url: jdbc:h2:file:~/dasboot
    username: sa
    password:
    driver-class-name: org.h2.Driver


multipart:
  maxFileSize: 50MB
  maxRequestSize: 50MB
  location: ${java.io.tmpdir}

logging:
  charset: UTF-8
  level:
    org.springframework.web: DEBUG

